// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgjvdosecinpgbfkectl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnanZkb3NlY2lucGdiZmtlY3RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODc5NDAsImV4cCI6MjA2NzY2Mzk0MH0.SmcP-ZrfBeSr6ptZLMqRGMVTNbnjX9kFOXBFyvlTBAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});